name: Daily Macro Email


on:
  workflow_dispatch:
  schedule:
    # 8:30 AM ET == 12:30 UTC (DST) or 13:30 UTC (Standard Time)
    - cron: "30 12 * * 1-5" # Weekdays during DST
    - cron: "30 13 * * 1-5" # Weekdays after DST ends


jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      SENDER_APP_PASSWORD: ${{ secrets.SENDER_APP_PASSWORD }}
      RECIPIENTS: ${{ secrets.RECIPIENTS }}
      TIMEZONE: America/New_York
      MODEL: gpt-4o-mini
      # If you prefer running hourly and gating inside Python, set this to true.
      ENFORCE_830_ET: "false"
    steps:
      - uses: actions/checkout@v4
  
  
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      
      - name: Run daily sender
        run: python run_daily.py
      
      
      - name: Archive audit bundle
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: audit-${{ github.run_id }}
          path: .out/*.json
          if-no-files-found: ignore
